apiVersion: builtin
kind: LabelTransformer
metadata:
  name: version
labels:
  app.kubernetes.io/version: $(PVPOOL_VERSION)
fieldSpecs:
- path: metadata/labels
  create: true
- group: apps
  kind: Deployment
  path: spec/template/metadata/labels
  create: true
